pretrained_model_path: ./checkpoints/CompVis/stable-diffusion-v1-4
output_dir: /content/drive/Shareddrives/CSE599/outputs/lucia/
train_data:
  video_path: data/lucia.mp4
  prompt: A young woman in black dress is walking along a country road
  n_sample_frames: 8
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 2
validation_data:
  prompts:
  - mickey mouse is skiing on the snow
  - spider man is skiing on the beach, cartoon style
  - wonder woman, wearing a cowboy hat, is skiing
  - a man, wearing pink clothes, is skiing at sunset
  video_length: 8
  width: 512
  height: 512
  num_inference_steps: 20
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 300
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
